/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.gerenciadorTarefa;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class FrTarefas extends javax.swing.JFrame {

    /**
     * Creates new form FrTarefas
     */
    public FrTarefas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtTarefa = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTarefa = new javax.swing.JTextArea();
        btnEditar = new javax.swing.JButton();
        btnVisuzalizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnQuantidade = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnVazio = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnTopo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciador De Tarefas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insira a Tarefa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        edtTarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtTarefaKeyPressed(evt);
            }
        });
        jPanel1.add(edtTarefa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 389, -1));

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdicionar.setText("Adicionar\n");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tarefas Disponiveis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        txtTarefa.setColumns(20);
        txtTarefa.setRows(5);
        jScrollPane1.setViewportView(txtTarefa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 400, 250));

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setText("Editar\n");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 90, 30));

        btnVisuzalizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisuzalizar.setText("Visualizar");
        btnVisuzalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisuzalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisuzalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 30));

        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 100, 30));

        btnQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuantidade.setText("Quantidade");
        btnQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, 30));

        btnOrdenar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, 30));

        btnVazio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVazio.setText("Lista Vazia");
        btnVazio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVazioActionPerformed(evt);
            }
        });
        jPanel1.add(btnVazio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, 30));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 100, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/gerenciadorTarefa/img/1345063.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        btnTopo.setText("Priorizar Tarefa");
        btnTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Gerenciador tar = new Gerenciador();
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnVisuzalizar.doClick();
        int cod; 
        String novaTarefa;
        cod=Integer.parseInt(JOptionPane.showInputDialog("Qual o código da Tarefa?"));
        novaTarefa = JOptionPane.showInputDialog("Digite a nova tarefa");
        tar.editar((cod-1), novaTarefa);
        txtTarefa.setText(tar.visualizar());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVisuzalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisuzalizarActionPerformed
        txtTarefa.setText(tar.visualizar());
    }//GEN-LAST:event_btnVisuzalizarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        tar.adicionar(edtTarefa.getText());
        edtTarefa.setText("");
        edtTarefa.requestFocus();
        txtTarefa.setText(tar.visualizar());
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        btnVisuzalizar.doClick();
        int remov=0;
        remov=Integer.parseInt(JOptionPane.showInputDialog("Qual tarefa você deseja Remover?"));
      if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover a tarefa?","confirma",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
          tar.remover(remov-1);
      }else{
          JOptionPane.showMessageDialog(null, "Exclusão cancelada!");
      }
        
       txtTarefa.setText(tar.visualizar());
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        btnVisuzalizar.doClick();
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Limpar as tarefas?","confirma",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            tar.limparTarefas();
            JOptionPane.showMessageDialog(null, "Lista de tarefas limpa!!");
        }else{
            JOptionPane.showMessageDialog(null, "Limpar Tarefas cancelado!");
        }
        txtTarefa.setText(null);
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void edtTarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtTarefaKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            btnAdicionar.doClick();
        }
    }//GEN-LAST:event_edtTarefaKeyPressed

    private void btnQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantidadeActionPerformed
        tar.QuantidadeTarefas();
        txtTarefa.setText(tar.visualizar());
    }//GEN-LAST:event_btnQuantidadeActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        tar.ordenarTarefas();
        txtTarefa.setText(tar.visualizar());
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnVazioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVazioActionPerformed
        tar.listaVazia();
        txtTarefa.setText(tar.visualizar());
    }//GEN-LAST:event_btnVazioActionPerformed

    private void btnTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopoActionPerformed
 btnVisuzalizar.doClick();
        tar.priorizar();
        btnVisuzalizar.doClick();
    }//GEN-LAST:event_btnTopoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnQuantidade;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnTopo;
    private javax.swing.JButton btnVazio;
    private javax.swing.JButton btnVisuzalizar;
    private javax.swing.JTextField edtTarefa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTarefa;
    // End of variables declaration//GEN-END:variables
}
